services:
  app:
    image: node:24-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 127.0.0.1:3078:3078
    working_dir: /app
    volumes:
      - ./:/app
  db:
    image: postgres:latest
    ports: 
      - 127.0.0.1:XXX:XXX
    environment:
      POSTGRES_PASSWORD: XXX
      POSTGRES_USER: XXX
      POSTGRES_DB: XXX